-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
id INTEGER primary key generated by default as identity,
title text,
rating numeric,
description text,
url VARCHAR(255) 
);



-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, rating, description, url)
values
('google', '5', 'a google site', 'http://www.google.com'),
('yahoo', '4', 'a yahoo site', 'http://www.yahoo.com'),
('IE', '3', 'a IE site', 'http://www.IE.com'),
('fake', '1', 'a fake site', 'http://www.fake.com'),
('something', '3', 'a demo site', 'http://www.demo.com');
